name: renovate

concurrency:
  group: renovate
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0/30 * * * *'

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  run:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/renovatebot/renovate:40.33.8
      options: -u 0:0

    steps:
      - id: config
        run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then
            echo "RENOVATE_DRY_RUN=full" >>"$GITHUB_ENV"
            if [ "$(jq .pull_request.base.repo.node_id "$GITHUB_EVENT")" = "$(jq .pull_request.head.repo.node_id "$GITHUB_EVENT")" ]; then
              echo "RENOVATE_BASE_BRANCHES=$GITHUB_HEAD_REF" >>"$GITHUB_ENV"
              echo "RENOVATE_USE_BASE_BRANCH_CONFIG=merge" >>"$GITHUB_ENV"
            fi
          fi

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: renovate

      - run: renovate
        env:
          LOG_LEVEL: debug
          GITHUB_COM_TOKEN: ${{ github.token }}
          RENOVATE_TOKEN: ${{ github.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_REPORT_TYPE: logging
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_BASE_DIR: ${{ github.workspace }}
          RENOVATE_CACHE_DIR: ${{ github.workspace }}/cache

      - uses: actions/cache/save@v4
        with:
          path: cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
