name: renovate

concurrency:
  group: renovate
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  issues:
    types:
      - edited
  schedule:
    - cron: '0/30 * * * *'

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  run:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/renovatebot/renovate:40.33.8
      options: -u 0:0

    if: >-
      github.event.issue.title == 'Dependency Dashboard' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' || (
        github.event_name == 'pull_request' &&
        github.event.pull_request.base.repo.node_id == github.event.pull_request.head.repo.node_id &&
        (github.event.action == 'edited') == startsWith(github.head_ref, 'renovate/')
      ) || (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.base.repo.node_id != github.event.pull_request.head.repo.node_id &&
        github.event.action != 'edited'
      )

    steps:
      - run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then
            echo "RENOVATE_DRY_RUN=full" >>"$GITHUB_ENV"
            if [ "$(jq .pull_request.base.repo.node_id "$GITHUB_EVENT_PATH")" = "$(jq .pull_request.head.repo.node_id "$GITHUB_EVENT_PATH")" ]; then
              echo "RENOVATE_BASE_BRANCHES=$GITHUB_HEAD_REF" >>"$GITHUB_ENV"
            else
              echo "RENOVATE_BASE_BRANCHES=$GITHUB_BASE_REF" >>"$GITHUB_ENV"
            fi
            echo "RENOVATE_USE_BASE_BRANCH_CONFIG=merge" >>"$GITHUB_ENV"
          elif [ "$GITHUB_REF_NAME" != "$(jq .repository.default_branch "$GITHUB_EVENT_PATH")" ]; then
            echo "RENOVATE_DRY_RUN=full" >>"$GITHUB_ENV"
            echo "RENOVATE_BASE_BRANCHES=$GITHUB_REF_NAME" >>"$GITHUB_ENV"
            echo "RENOVATE_USE_BASE_BRANCH_CONFIG=merge" >>"$GITHUB_ENV"
          fi

      - uses: actions/cache@v4
        with:
          path: cache
          key: renovate

      - run: renovate
        env:
          LOG_LEVEL: debug
          FORCE_COLOR: '2'
          GITHUB_COM_TOKEN: ${{ github.token }}
          RENOVATE_TOKEN: ${{ github.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_REPORT_TYPE: logging
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_BASE_DIR: ${{ github.workspace }}
          RENOVATE_CACHE_DIR: ${{ github.workspace }}/cache
