name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  renovate:
    uses: ./.github/workflows/dry-run.yml
    with:
      app-id: 1336158
    secrets:
      private-key: ${{ secrets.SELF_HOSTED_RENOVATE_KEY }}

  check-diff:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request_target'

    steps:
      - uses: actions/checkout@v4

      - run: |
          set +e; diff -d -y --suppress-common-lines .github/workflows/update.yml .github/workflows/dry-run.yml >expected.diff
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 1 ]; then
            exit $status
          fi

      - run: git diff --color --exit-code -- expected.diff
