name: renovate

on:
  workflow_dispatch:
  pull_request:
  pull_request_target:

jobs:
  reusable:
    uses: ./.github/workflows/dry-run.yml
    with:
      app-id: 1336158
    secrets:
      private-key: ${{ secrets.SELF_HOSTED_RENOVATE_KEY }}
